### ISSUE TITLE
Cannot set http_no_proxy without also setting http_proxy_host and http_proxy_port

### ISSUE THREAD

**Issue by mbrzv** [websocket-client/websocket-client#585]
I am having issues getting this library to ignore the proxy.  In my example, I have a target running on a private network interface.  I do not want it to use the proxy in this case.  

When I try this:
```
from websocket import create_connection
self.conn = create_connection('ws://192.168.2.159:8181', timeout=1)
```
I receive a 503 due to the proxy.  Very frustrating - is there a way to tell it to just _completely_ ignore the proxy?

Sadly, even this does not work:
```
from websocket import create_connection
self.conn = create_connection('ws://192.168.2.159:8181', timeout=1, http_no_proxy='192.168.2.159')
```

I need to specify all 3 to get it to work.

```
from websocket import create_connection
self.conn = create_connection('ws://192.168.2.159:8181', timeout=1, http_proxy_host="proxy.site.com", http_proxy_port=8181, http_no_proxy='192.168.2.159')
```
I do not want to do this.  How do I avoid it?

**Comment by engn33r** [comment]
Unfortunately I do not fully understand the environment you are working in. You mentioned that you want to "ignore the proxy" - where is this proxy information coming from? This sounds like an issue with managing the proxy settings that are being inherited by Python. I haven't dealt with such a situation before, so I will likely be unable to offer much of a solution, but perhaps someone else can assist if you can provide further information about the proxy setup you have.

**Comment by engn33r** [comment]
I think this issue should be fixed thanks to PR #671, which fixed the no_proxy logic. Please share if that is not the case and we can reopen this issue.

**Comment by pawamoy** [comment]
Typically most tools respect the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` variables. It seems that websocket-client doesn't respect `NO_PROXY`?

Same thing happened to me in a corporate environment: I wanted to create a web socket connection to a internal server ending in `internal.fr` while my env var `NO_PROXY` is `localhost,internal.fr`, and was getting `Handshake status 403 forbidden` error messages. As soon as I ran my Python script with `HTTP_PROXY= HTTPS_PROXY= python script.py`, it worked, showing me the connection was passing through the proxy while it shouldn't have.

**Comment by pawamoy** [comment]
Ah, #671 does seem to fix it, though I still experienced this issue with version 1.0.1 😕

**Comment by engn33r** [comment]
@pawamoy the `_is_no_proxy_host()` function in _url.py contains the code `os.environ.get("no_proxy", "")`. Do you get the expected result when you use the lowercase `no_proxy` env variable? If the issue is case sensitivity, I can look at how to ignore case with os.environ variables. If the env variable is read properly but the websocket-client code doesn't use the variable correctly, it would be best to create a new issue with the info outlined in [the contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md).
